class AppUnq {
  static Map UnqCode = {
    'MOB_FW_WHITETIGER_120': {'name': 'Manho', 'points': 20},
    'MOB_MAXIGAME_KARA_KING_MOLE': {'name': 'The King Mole', 'points': 20},
    'MOB_GOD_FLAME_GIGANTIC_B4': {'name': 'Flame Gigante', 'points': 20},
    'MOB_GOD_TOGUI_TOGUIDOLL_C2': {'name': 'Togui Doll', 'points': 20},
    'MOB_FW_HANGA_120': {'name': 'Hang-A', 'points': 20},
    'MOB_FW_HANGA_100': {'name': 'Hang-A', 'points': 20},
    'MOB_FW_HANGA_110': {'name': 'Hang-A', 'points': 20},
    'MOB_RM_SPIRITS_CLON': {'name': 'Salamander', 'points': 20},
    'MOB_RM_SPIRITS': {'name': 'Undine', 'points': 20},
    'MOB_RM_SPIRITS_CLON2': {'name': 'Sylph', 'points': 20},
    'MOB_RM_DEVILSAYTAN': {'name': 'Devil Shaitan', 'points': 20},
    'MOB_FW_TAESE_120': {'name': 'Tai-Sui', 'points': 20},
    'MOB_FW_TAESE_100': {'name': 'Tai-Sui', 'points': 20},
    'MOB_FW_DARKEAGLE_120': {'name': 'Black Cloud', 'points': 20},
    'MOB_FW_KYKLOPES_120': {'name': 'Cyclops', 'points': 20},
    'MOB_FW_HYEONGCHEON_120': {'name': 'Senior General', 'points': 20},
    'MOB_FW_MUJIGI_120': {'name': 'Rage Cloud', 'points': 20},
    'MOB_FW_HAGIAZO_120': {'name': 'Ganiazo Dow', 'points': 20},
    'MOB_FW_BATTLEGOLEM_120': {'name': 'Battle Golem', 'points': 20},
    'MOB_JUPITER_THE_EARTH1': {'name': 'The Earth', 'points': 20},
    'MOB_JUPITER_THE_EARTH2': {'name': 'The Earth', 'points': 20},
    'MOB_JUPITER_YUNO': {'name': 'YUNO', 'points': 20},
    'MOB_JUPITER_BAAL': {'name': 'BAAL', 'points': 20},
    'MOB_JUPITER_DARK_DOG': {'name': 'Zielkiaxe', 'points': 20},
    'MOB_JUPITER_BABILION': {'name': 'BABILION', 'points': 20},
    'MOB_SD_APIS': {'name': 'Apis', 'points': 20},
    'MOB_CH_MANGNYANG_EVIL': {'name': 'Evil Mangyang', 'points': 20},
    'MOB_CH_TIGERWOMAN': {'name': 'Tiger Girl', 'points': 20},
    'MOB_EU_KERBEROS': {'name': 'Cerberus', 'points': 20},
    'MOB_KK_ISYUTARU': {'name': 'Isyutaru', 'points': 20},
    'MOB_OA_URUCHI': {'name': 'Uruchi', 'points': 20},
    'MOB_RM_TAHOMET': {'name': 'Demon Shaitan', 'points': 20},
    'MOB_TK_BONELORD': {'name': 'Lord Yarkan', 'points': 20},
    'MOB_TQ_BLACKSNAKE': {'name': 'SoSo The Black Viper', 'points': 20},
    'MOB_CH_TIGERWOMAN_L3': {'name': 'Tiger Girl (Titan)', 'points': 20},
    'MOB_EU_KERBEROS_L3': {'name': 'Cerberus (Titan)', 'points': 20},
    'MOB_KK_ISYUTARU_L3': {'name': 'uniquIsyutaru (Titan)ename', 'points': 20},
    'MOB_OA_URUCHI_L3': {'name': 'Uruchi (Titan)', 'points': 20},
    'MOB_RM_TAHOMET_L3': {'name': 'Demon Shaitan (Titan)', 'points': 20},
    'MOB_TK_BONELORD_L3': {'name': 'Lord Yarkan (Titan)', 'points': 20},
    'MOB_CH_TIGERWOMAN_INT': {'name': 'Tiger Girl (INT)', 'points': 20},
    'MOB_ARABIA_MUSTAFA1': {'name': 'PWO Geenie', 'points': 20},
    'MOB_ARABIA_MUSTAFA2': {'name': 'PWO Launatune', 'points': 20},
    'MOB_ARABIA_MUSTAFA3': {'name': 'PWO Harrison', 'points': 20},
    'MOB_ARABIA_MUSTAFA4': {'name': 'PWO Venefica (S)', 'points': 20},
    'MOB_ARABIA_MUSTAFA5': {'name': 'Demon Venefica', 'points': 20},
    'MOB_SD_ANUBIS': {'name': 'Anubis', 'points': 20},
    'MOB_RM_BONEROC': {'name': 'Bone roc', 'points': 20},
    'MOB_RM_ROC': {'name': 'Roc', 'points': 20},
    'MOB_TQ_WHITESNAKE': {'name': 'BeakYung The White Viper', 'points': 20},
    'MOB_ARABIA_KARKADANN': {'name': 'Karkadann', 'points': 20},
    'MOB_ARABIA_KHULOOD': {'name': 'Khulood', 'points': 20},
    'MOB_ARABIA_KIDEMONAS': {'name': 'Kidemonas', 'points': 20},
    'MOB_ARABIA_THIEF_BOSS': {'name': 'Thief Boss', 'points': 20},
    'MOB_JUPITER_JUPITER': {'name': 'Jupiter', 'points': 20},
    'MOB_SD_HAROERIS': {'name': 'Haroeris', 'points': 20},
    'MOB_SD_SETH': {'name': 'Seth', 'points': 20},
    'MOB_SD_NEITH': {'name': 'Neith', 'points': 20},
    'MOB_SD_SELKIS': {'name': 'Selket', 'points': 20},
    'MOB_SD_ISIS': {'name': 'Isis', 'points': 20},
    'MOB_ARABIA_GIANT_DEMON': {'name': 'Giant Demon', 'points': 20},
    'MOB_AM_IVY': {'name': 'Captain Ivy', 'points': 20},
    'MOB_CH_TIGERWOMAN_STR': {'name': 'Tiger Girl (STR)', 'points': 20},
    'MOB_ROC_INT': {'name': 'Roc(INT)', 'points': 20},
    'MOB_ROC_STR': {'name': 'Roc (STR)', 'points': 20},
    'MOB_OA_URUCHI_STR': {'name': 'Uruchi (STR)', 'points': 20},
    'MOB_OA_URUCHI_INT': {'name': 'Uruchi (INT)', 'points': 20},
    'MOB_KK_ISYUTARU_STR': {'name': 'Isyutaru (STR)', 'points': 20},
    'MOB_KK_ISYUTARU_INT': {'name': 'Isyutaru (INT)', 'points': 20},
    'MOB_TK_BONELORD_STR': {'name': 'Lord Yarkan (STR)', 'points': 20},
    'MOB_TK_BONELORD_INT': {'name': 'Lord Yarkan (INT)', 'points': 20},
    'MOB_RM_TAHOMET_STR': {'name': 'Demon Shaitan (STR)', 'points': 20},
    'MOB_RM_TAHOMET_INT': {'name': 'Demon Shaitan (INT)', 'points': 20},
    'MOB_EU_KERBEROS_STR': {'name': 'Cerberus (STR)', 'points': 20},
    'MOB_EU_KERBEROS_INT': {'name': 'Cerberus (INT)', 'points': 20},
    'MOB_AM_IVY_STR': {'name': 'Captain Ivy (STR)', 'points': 20},
    'MOB_AM_IVY_INT': {'name': 'Captain Ivy (INT)', 'points': 20},
    'MOB_TQ_WHITESNAKE_STR': {
      'name': 'BeakYung The White Viper ( STR )',
      'points': 20
    },
    'MOB_TQ_WHITESNAKE_INT': {
      'name': 'BeakYung The White Viper ( INT )',
      'points': 20
    },
    'MOB_SD_ERIS': {'name': 'Eris', 'points': 20},
    'MOB_FW_BIGSPIDER_120': {'name': 'Taishan Monster', 'points': 20},
    'MOB_SD_SPHINX': {'name': 'Sphinx', 'points': 20},
    'MOB_SD_SEKHMET': {'name': 'Sekhmet', 'points': 20},
    'MOB_SD_NEPHTHYS': {'name': 'Nephthys', 'points': 20},
    'MOB_SD_HORUS': {'name': 'Horus', 'points': 20},
    'MOB_SD_OSIRIS': {'name': 'Osiris', 'points': 20},
  };
}
